FROM ubuntu:18.04

RUN apt update \
    && apt install nginx -y

COPY prometheus.crt prometheus.key /opt/
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443
CMD ["nginx","-g","daemon off;"]

